# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f98794030efb5ec233cab20de0a69edbc893cd5d6cba1938737eb15560e7fe2110c5707e249858ccad64dc1f16cccf274a15d42e332a3ad2bbabe545245d0b1e

dai:
  secret_key_base: f98794030efb5ec233cab20de0a69edbc893cd5d6cba1938737eb15560e7fe2110c5707e249858ccad64dc1f16cccf274a15d42e332a3ad2bbabe545245d0b1e

test:
  secret_key_base: f9fc5c6ebd4cb3e7cbc09e8e2cdb81709e8ab9bedadd03a055e91ed8ed931d48620ee3d4c6fe4f6b95cc47590dfb051f40d6db17596e16af885894cd400de31d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
